# yaml-language-server: $schema=https://taskfile.dev/schema.json
# Created: 20 Aug 2026
# Updated: 20 Aug 2026
# Developer: LordOfScripts™
# Examples:
#   - task mlog_demo BUILD_TYPE=develop
#   - task mlog_demo
version: '3'

vars:
  # ⚙️ Task 'MLog Demo' build paths
  SRC_MLOG: cmd/examples/demo_mlog
  BIN_MLOG: bin/demo_mlog
  # ⚙️ Task 'ZLog Demo' build paths
  SRC_ZLOG: cmd/examples/demo_zlog
  BIN_ZLOG: bin/demo_zlog
  # ⚙️ Task 'GoApp Demo' build paths
  SRC_APP: cmd/examples/demo_app
  BIN_APP: bin/demo_app  
  # ⚙️ Task 'Info' Software Distribution Information
  PKG_NAME: goapp
  PKG_PREFERRED_ARCH: amd64
  PKG_REVISION: '1'
  # 🚫 Off-limits
  GREETING: 🔱 Greetings from LordOfScripts™ 🔱
  # Build type: 'debug' (default is release)
  BUILD_TYPE: '{{.BUILD_TYPE | default ""}}'  
  PKG_SEMANTIC_VERSION:
    sh: |
      sed -n '/>>>BEGIN/,/>>>END/p' version.go > /tmp/mainversion_gap.go &&
      go run /tmp/mainversion_gap.go short
  PKG_FULL_VERSION:
    sh: |
      sed -n '/>>>BEGIN/,/>>>END/p' version.go > /tmp/mainversion_gap.go &&
      go run /tmp/mainversion_gap.go version
  PKG_PUBLIC_NAME: 
    sh: go list -m
  PKG_FULLNAME: '{{.PKG_NAME}}_{{.PKG_FULL_VERSION}}-{{.PKG_REVISION}}-{{.PKG_PREFERRED_ARCH}}'

tasks:
  default:
    desc: Print a greeting message
    cmds:
      - echo -e "\t{{.GREETING}}\n\tAre you lost?\n\t☕️ https://buymeacoffee.com/lostinwriting"
    silent: true

  # Build MLog Demo (Task)
  mlog_demo:
    desc: Sample demonstration of MLog
    cmds:
      - echo "{{.GREETING}}"
      - |
        case "{{.BUILD_TYPE}}" in
          debug)
            go build -tags mlog,develop -v -o {{.BIN_MLOG}}_dev {{.SRC_MLOG}}/*.go 2>&1 | $HOME/go/bin/gocolor -color -width 75 -version
            ;;
          *)
            go build -tags mlog -v -o {{.BIN_MLOG}} {{.SRC_MLOG}}/*.go 2>&1 | $HOME/go/bin/gocolor -color -width 75 -version
            ;;
        esac
      - echo "delivered {{.BIN_MLOG}}"
    silent: true

  # Build ZLog Demo (Task)
  zlog_demo:
    desc: Sample demonstration of ZLog (Flexible logger)
    cmds:
      - echo "{{.GREETING}}"
      - |
        case "{{.BUILD_TYPE}}" in
          debug)
            go build -tags zlog,develop -v -o {{.BIN_ZLOG}}_dev {{.SRC_ZLOG}}/*.go 2>&1 | $HOME/go/bin/gocolor -color -width 75 -version
            ;;
          *)
            go build -tags zlog -v -o {{.BIN_ZLOG}} {{.SRC_ZLOG}}/*.go 2>&1 | $HOME/go/bin/gocolor -color -width 75 -version
            ;;
        esac
      - echo "delivered {{.BIN_ZLOG}}"
    silent: true

  # Build GoApp Demo (Task)
  goapp_demo:
    desc: Sample demonstration of root GoApp capabilities
    cmds:
      - echo "{{.GREETING}}"
      - |
        case "{{.BUILD_TYPE}}" in
          debug)
            go build -tags mlog,develop -v -o {{.BIN_APP}}_dev {{.SRC_APP}}/*.go 2>&1 | $HOME/go/bin/gocolor -color -width 75 -version
            ;;
          *)
            go build -tags mlog -v -o {{.BIN_APP}} {{.SRC_APP}}/*.go 2>&1 | $HOME/go/bin/gocolor -color -width 75 -version
            ;;
        esac
      - echo "delivered {{.BIN_APP}}"
    silent: true

  # Publish Package (Task)
  publish:
    desc: Publish package via GO PROXY
    cmds:
      - GOPROXY=proxy.golang.org go list -m {{.PKG_PUBLIC_NAME}}@v{{.PKG_FULL_VERSION}}

  # Run Tests (Task)
  test:
    desc: Regression and Unit Tests
    cmds:
      - go test -v tests/*_test.go
  
  # Clean binaries (Task)
  clean:
    desc: Remove all output binaries
    cmds:
      - rm -f bin/*

  # Software Information (Task)
  info:
    desc: General information about this Software
    cmds:
      - 'echo -e "\tSemantic version: {{.PKG_SEMANTIC_VERSION}}"'
      - 'echo -e "\tFull version: {{.PKG_FULL_VERSION}}"'
      - 'echo -e "\tModule name: {{.PKG_PUBLIC_NAME}}"'
      - 'echo -e "\tPackage name: {{.PKG_FULLNAME}}"'
    silent: true      